# Description

## Summary of Changes

If your PR summary is AI-generated, it will be closed.

Fixes # (issue)

## Screenshot

Upload a screenshot if applicable, otherwise remove this section.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have run tests (npm run test) that prove my fix is effective or that my feature works
